apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-sc-mon"
  namespace: "local-storage"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - sto-1.ocp.datacenter.com
          - sto-2.ocp.datacenter.com
          - sto-3.ocp.datacenter.com
  storageClassDevices:
    - storageClassName: "local-sc-mon"
      volumeMode: Filesystem
      fsType: xfs
      devicePaths:
        - /dev/sdb
